### ISSUE TITLE
Sidebar links broken on learninglocker.github.io

### ISSUE THREAD

**Issue by rklancer** [LearningLocker/docs#12]
Click on any sidebar link at http://learninglocker.github.io/docs/ (say, "Contributors") - you're sent to http://learninglocker.github.io/contributors instead of http://learninglocker.github.io/docs/contributors

I've been reading the docs by manually inserting "docs" into the URL

**Comment by rklancer** [comment]
Of course another workaround is to manually click on the `.md` files

**Comment by ryansmith94** [comment]
This is not broken. You're using the wrong URL, go to [docs.learninglocker.net](http://docs.learninglocker.net/).

**Comment by ee0pdt** [comment]
Thanks for reporting this. I've raised it with our team lead on this project

**Comment by rklancer** [comment]
Ah I see you do have a `CNAME` pointing to http://docs.learninglocker.net/
