### ISSUE TITLE
client username and password split over two lines in LL, extra space

### ISSUE THREAD

**Issue by twelch555** [LearningLocker/docs#20]
Hi, just finished troubleshooting a "cannot connect" error for one of our people on campus. A copy and paste from LL client screen to grassblade plugin in Wordpress leaves an extra character in username and password. It coincides with the line break (<br> tag) on the LL client screen.

Our issue is solved but it may be something to look at.

**Comment by ryansmith94** [comment]
Hi @twelch555, thanks for reporting this. We are aware of this issue, it's just been a low priority a compared to other tasks in this project and our other projects. What version of Learning Locker are you using (it should say towards the bottom left of your screen)?
